In [1]:
from absenteeism_module import *

In [2]:
pd.read_csv('Absenteeism_new_data.csv')

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0
5,28,11,11/06/2018,225,26,28,237.656,24,1,1,2
6,16,7,13/06/2018,118,15,46,275.089,25,1,2,0
7,22,27,13/06/2018,179,26,30,275.089,19,3,0,0
8,34,26,15/06/2018,118,10,37,275.089,28,1,0,0
9,34,10,20/06/2018,118,10,37,275.089,28,1,0,0
10,23,22,21/06/2018,378,49,36,275.089,21,1,2,4
11,36,19,21/06/2018,118,13,50,275.089,31,1,1,0
12,12,19,22/06/2018,233,51,31,275.089,21,2,1,8
13,22,27,22/06/2018,179,26,30,275.089,19,3,0,0
14,2,0,25/06/2018,235,29,48,275.089,33,1,1,5
15,21,0,28/06/2018,268,11,33,275.089,25,2,0,0
16,36,19,28/06/2018,118,13,50,275.089,31,1,1,0
17,22,13,28/06/2018,179,26,30,275.089,19,3,0,0
18,15,28,28/06/2018,291,31,40,275.089,25,1,1,1
19,22,13,02/07/2018,179,26,30,275.089,19,3,0,0
20,34,25,02/07/2018,118,10,37,275.089,28,1,0,0
21,12,22,05/07/2018,233,51,31,275.089,21,2,1,8
22,34,8,06/07/2018,118,10,37,275.089,28,1,0,0
23,34,10,11/07/2018,118,10,37,275.089,28,1,0,0
24,12,22,11/07/2018,233,51,31,275.089,21,2,1,8
25,5,26,11/07/2018,235,20,43,264.604,38,1,1,0
26,12,19,13/07/2018,233,51,31,264.604,21,2,1,8
27,9,6,16/07/2018,228,14,58,264.604,22,1,2,1
28,34,28,16/07/2018,118,10,37,264.604,28,1,0,0
29,9,6,17/07/2018,228,14,58,264.604,22,1,2,1
30,6,22,17/07/2018,189,29,33,264.604,25,1,2,2
31,34,23,18/07/2018,118,10,37,264.604,28,1,0,0
32,10,22,18/07/2018,361,52,28,264.604,27,1,1,4
33,28,22,18/07/2018,225,26,28,264.604,24,1,1,2
34,13,13,23/07/2018,369,17,31,264.604,25,1,3,0
35,11,14,24/07/2018,289,36,33,264.604,30,1,2,1
36,1,11,24/07/2018,235,11,37,264.604,29,3,1,1
37,4,0,24/07/2018,118,14,40,271.219,34,1,1,8
38,8,0,25/07/2018,231,35,39,271.219,35,1,2,2
39,35,0,27/07/2018,179,45,53,271.219,25,1,1,1

In [3]:
# create instance of the model class with arguments
model = absenteeism_model('model', 'scaler')

/Users/mk/6303/envs/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LogisticRegression from version 1.0.2 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/mk/6303/envs/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator StandardScaler from version 1.0.2 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [4]:
model.load_and_clean_data('Absenteeism_new_data.csv')

In [5]:
model.predicted_outputs()

/Users/mk/6303/envs/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)
/Users/mk/6303/envs/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.462915,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.692057,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.258066,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.411592,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.712007,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.737730,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.821531,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.462915,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.382517,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.814923,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.310808,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.877630,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.941359,1
13,0,0.0,0,1,6,179,30,19,1,0,0,0.462915,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.278840,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.200815,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.877630,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.859674,1
18,0,0.0,0,1,6,291,40,25,0,1,1,0.319652,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.879256,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.424076,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.661984,1
22,1,0.0,0,0,7,118,37,28,0,0,0,0.839584,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.839584,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.661984,1
25,0,0.0,0,1,7,235,43,38,0,1,0,0.252104,0
26,0,0.0,1,0,7,233,31,21,1,1,8,0.950202,1
27,1,0.0,0,0,7,228,58,22,0,2,1,0.902845,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.424076,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.902845,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.322674,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.424076,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.273164,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.319911,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.536944,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.640912,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.823569,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.384864,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.127862,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.362675,0

In [6]:
import pymysql

In [7]:
conn = pymysql.connect(database = 'predicted_outputs', user = 'root', password = '********')

In [8]:
cursor = conn.cursor()

In [9]:
#checkpoint
df_new_obs = model.predicted_outputs()
df_new_obs

/Users/mk/6303/envs/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)
/Users/mk/6303/envs/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.462915,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.692057,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.258066,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.411592,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.712007,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.737730,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.821531,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.462915,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.382517,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.814923,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.310808,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.877630,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.941359,1
13,0,0.0,0,1,6,179,30,19,1,0,0,0.462915,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.278840,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.200815,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.877630,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.859674,1
18,0,0.0,0,1,6,291,40,25,0,1,1,0.319652,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.879256,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.424076,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.661984,1
22,1,0.0,0,0,7,118,37,28,0,0,0,0.839584,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.839584,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.661984,1
25,0,0.0,0,1,7,235,43,38,0,1,0,0.252104,0
26,0,0.0,1,0,7,233,31,21,1,1,8,0.950202,1
27,1,0.0,0,0,7,228,58,22,0,2,1,0.902845,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.424076,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.902845,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.322674,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.424076,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.273164,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.319911,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.536944,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.640912,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.823569,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.384864,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.127862,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.362675,0

In [10]:
#.execute()

In [11]:
cursor.execute('SELECT * FROM predicted_outputs;')

0

In [12]:
#create the INSERT statement

In [13]:
insert_query = 'INSERT INTO predicted_outputs VALUES '

In [14]:
insert_query

'INSERT INTO predicted_outputs VALUES '

In [15]:
#explore data extraction methods
df_new_obs.shape

(40, 13)

In [16]:
df_new_obs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Probability', 'Prediction'], dtype=object)

In [17]:
df_new_obs.columns.values[6]

'Age'

In [18]:
df_new_obs[df_new_obs.columns.values[6]][0]

30

In [19]:
df_new_obs['Age']

0     30
1     28
2     34
3     40
4     34
5     28
6     46
7     30
8     37
9     37
10    36
11    50
12    31
13    30
14    48
15    33
16    50
17    30
18    40
19    30
20    37
21    31
22    37
23    37
24    31
25    43
26    31
27    58
28    37
29    58
30    33
31    37
32    28
33    28
34    31
35    33
36    37
37    40
38    39
39    53
Name: Age, dtype: int64

In [20]:
for i in range(df_new_obs.shape[0]):
    insert_query += '('
    
    for j in range(df_new_obs.shape[1]):
        insert_query += str(df_new_obs[df_new_obs.columns.values[j]][i]) + ', '
        
    insert_query = insert_query[:-2] + '), '

In [21]:
insert_query

'INSERT INTO predicted_outputs VALUES (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.46291541258064545, 0), (1, 0.0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.6920568416640256, 1), (0, 0.0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.2580664067303971, 0), (0, 0.0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.4115922496568379, 0), (1, 0.0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7120074377727318, 1), (1, 0.0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.7377297285123886, 1), (1, 0.0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.821531184106428, 1), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.46291541258064545, 0), (0, 0.0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.3825174091518623, 0), (1, 0.0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.8149227163179207, 1), (0, 0.0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.3108075853119483, 0), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.8776296520002305, 1), (0, 0.0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.9413588781930143, 1), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.46291541258064545, 0), (0, 0.0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.2788404315759027, 0), (0, 0.0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.20081459319971287, 0), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.8776296520002305, 1), (1, 0.0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.8596740344492255, 1), (0, 0.0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.31965228474650575, 0), (1, 0.0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.8792556162269775, 1), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.4240762312507767, 0), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.6619844876682315, 1), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.8395837760503846, 1), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.8395837760503846, 1), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.6619844876682315, 1), (0, 0.0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.2521044490338723, 0), (0, 0.0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.9502021476424619, 1), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.90284466213991, 1), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.4240762312507767, 0), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.90284466213991, 1), (0, 0.0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.3226735105936181, 0), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.4240762312507767, 0), (0, 0.0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.2731639061762676, 0), (0, 0.0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.31991120936644474, 0), (1, 0.0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.5369437920345004, 1), (1, 0.0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.6409123117060072, 1), (1, 0.0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.823569120939265, 1), (0, 0.0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.3848642286462152, 0), (0, 0.0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.12786158252947158, 0), (0, 0.0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.3626745081583855, 0), '

In [22]:
insert_query = insert_query[:-2] + ';'
insert_query

'INSERT INTO predicted_outputs VALUES (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.46291541258064545, 0), (1, 0.0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.6920568416640256, 1), (0, 0.0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.2580664067303971, 0), (0, 0.0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.4115922496568379, 0), (1, 0.0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7120074377727318, 1), (1, 0.0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.7377297285123886, 1), (1, 0.0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.821531184106428, 1), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.46291541258064545, 0), (0, 0.0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.3825174091518623, 0), (1, 0.0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.8149227163179207, 1), (0, 0.0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.3108075853119483, 0), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.8776296520002305, 1), (0, 0.0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.9413588781930143, 1), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.46291541258064545, 0), (0, 0.0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.2788404315759027, 0), (0, 0.0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.20081459319971287, 0), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.8776296520002305, 1), (1, 0.0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.8596740344492255, 1), (0, 0.0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.31965228474650575, 0), (1, 0.0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.8792556162269775, 1), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.4240762312507767, 0), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.6619844876682315, 1), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.8395837760503846, 1), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.8395837760503846, 1), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.6619844876682315, 1), (0, 0.0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.2521044490338723, 0), (0, 0.0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.9502021476424619, 1), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.90284466213991, 1), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.4240762312507767, 0), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.90284466213991, 1), (0, 0.0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.3226735105936181, 0), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.4240762312507767, 0), (0, 0.0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.2731639061762676, 0), (0, 0.0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.31991120936644474, 0), (1, 0.0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.5369437920345004, 1), (1, 0.0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.6409123117060072, 1), (1, 0.0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.823569120939265, 1), (0, 0.0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.3848642286462152, 0), (0, 0.0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.12786158252947158, 0), (0, 0.0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.3626745081583855, 0);'

In [23]:
cursor.execute(insert_query)

40

In [24]:
conn.commit()

In [25]:
conn.close()